import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import Svolve from "../(global_components)/Svolve";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased flex justify-center items-center h-screen`}
      >
        <Image
          src="/backgraund/group.svg"
          alt="Backgraund"
          fill
          className=" object-cover fixed top-0 left-0 z-0"
        ></Image>
        <div className="z-10 bg-white rounded-2xl p-8 min-w-xl space-y-4">
          <Svolve />
          {children}
        </div>
      </body>
    </html>
  );
}
